### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by dilizarov** [tnrich/react-variable-height-infinite-scroller#13]
It would be great if this was also on Bower for integration with https://rails-assets.org/

**Comment by tnrich** [comment]
hey @dilizarov I've never used bower or rails before, so don't know where to start for implementing this functionality. I'd be happy to accept any PR's you'd like to make to enable this however. If you need help understanding anything about the repo I'd be happy to provide answers.

**Comment by dilizarov** [comment]
https://viget.com/extend/publishing-packages-to-npm-and-bower shows how to get it done.

It is really something the owner of a project would do. It is basically like npm. Most projects support npm and bower :).

**Comment by tnrich** [comment]
I'm surprised your package manager of choice doesn't support npm.. I think
I published it on bower. Want to check it out and make sure you can access
it?

**Comment by tnrich** [comment]
@dilizarov is the new github release working for you using bower? How should I check this..? 

Seems to be showing up on bower component search: http://bower.io/search/?q=react-variable-height

**Comment by dilizarov** [comment]
Yep, it works for me!

On Wednesday, November 11, 2015, Thomas Rich notifications@github.com
wrote:

> @dilizarov https://github.com/dilizarov is the new github release
> working for you using bower? How should I check this..?
> 
> Seems to be showing up on bower component search:
> http://bower.io/search/?q=react-variable-height
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tnrich/react-variable-height-infinite-scroller/issues/13#issuecomment-155700729
> .

## 

Sent from my Android

**Comment by tnrich** [comment]
Awesome :)
