### ISSUE TITLE
`npm install` is not enough to run project, lacking further instructions

### ISSUE THREAD

**Issue by engelfrost** [tnrich/react-variable-height-infinite-scroller#15]
If I run `npm install && npm run build` I get the following error: 

``` sh
> react-variable-height-infinite-scroller@3.3.3 build /home/josef/Code/react-variable-height-infinite-scroller
> babel InfiniteScroller.js -o index.js

sh: 1: babel: not found
```

I run `npm install babel-cli`, run `npm run build` again and get this error: 

``` sh
npm run build
> react-variable-height-infinite-scroller@3.3.3 build /home/josef/Code/react-variable-height-infinite-scroller
> babel InfiniteScroller.js -o index.js

ReferenceError: [BABEL] InfiniteScroller.js: Unknown option: /home/josef/Code/react-variable-height-infinite-scroller/.babelrc.stage
    at Logger.error (/home/josef/Code/react-variable-height-infinite-scroller/node_modules/babelcli/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/josef/Code/react-variable-height-infinitescroller/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.addConfig (/home/josef/Code/react-variable-height-infinite-scroller/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
...
```

I've tried with node v4.2.2 and v5.3.0. 

Is there something I've missed?

**Comment by tnrich** [comment]
Hey @engelfrost, sorry about that. I had babel installed globally so wasn't aware it was required in the package.json. I added it to the package.json, so if you pull, npm install, npm start, you should be on your way to running the repo. 

A lot of the confusion comes from the babel 6 upgrade which I haven't switched to yet, and is why when you manually installed babel-cli, things didn't work. I'm sure I'll get around to doing that someday, but not quite yet.

Anything else I can help with?

**Comment by tnrich** [comment]
Hey @engelfrost, did my change work for you?

**Comment by engelfrost** [comment]
Hi, I'm back after the weekend now, this works just fine!

**Comment by tnrich** [comment]
Great! Let me know if you need anything else :)
