### ISSUE TITLE
question: would this work with changing heights?

### ISSUE THREAD

**Issue by georgesboris** [tnrich/react-variable-height-infinite-scroller#17]
Hi, this is a question not an issue.

Would this module work with components that change their heights during their lifecycle?
For instance, if my component has hidden elements and they show/hide based on the component state.
Would that break the list behavior by any chance?

Sorry for not just testing it out. I'm kinda multitasking here, hopefully you "just know" the answer.

Thank you.

**Comment by tnrich** [comment]
Hey @georgesboris, that should not break the list behavior. The heights are never cached and the total scroll position is always calculated inexactly.

**Comment by georgesboris** [comment]
Thanks for the quick response!
