### ISSUE TITLE
Automated Release

### ISSUE THREAD

**Issue by dozoisch** [tnrich/react-variable-height-infinite-scroller#4]
Alright so for automated release, in other projects I've been using
- https://www.npmjs.com/package/mt-changelog for the changelog
- https://www.npmjs.com/package/release-script for automated release

The changelog obliges you to normalize the commit messages with tags in order to generate nice changelog, but that's not a bad thing I guess! This is how changelog will look like https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md

Tags are added, fixed, changed, removed.

release-script enables you to do

```
release --patch
release --minor
release --major
```

Which will automatically bump the version, commit, tag and publish to npm directly.

If that's ok with you I can include them. If not we can find another solution.

**Comment by tnrich** [comment]
Both changelog and automated release are fine with me. Thanks for all your suggestions!
