### ISSUE TITLE
Build Tools

### ISSUE THREAD

**Issue by dozoisch** [tnrich/react-variable-height-infinite-scroller#5]
I see that you are building with https://github.com/petehunt/jsx-loader but it's deprecated in favor of babel.

So I'd do a PR to switch to babeljs.io. We can then refactor to more ES6 stuff (like let & const), shorthand functions and etc., if you want!

**Comment by tnrich** [comment]
Babel sounds good! It looks like the airbnb guide recommends mostly es6 syntax, so I'm happy to switch to that.
