### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by dozoisch** [tnrich/react-variable-height-infinite-scroller#6]
Adding ESLint could be a good thing. It helps catching out some issues while coding (like forgotten console-log and etc). There are a few standards like https://github.com/airbnb/javascript, or https://github.com/Flet/semistandard or we can make a custom eslint config. I don't really mind, but I do think using a standard that is widely use helps for future contribution!

Let me know what would fit the best, and I'll add it!

**Comment by tnrich** [comment]
Hey @dozoisch, the airbnb guidelines are a nice read. I'd be happy to go with their js standards. Is it just a jslintrc that they use? Or do they have their own version of Standard they implement?

**Comment by dozoisch** [comment]
It's a package for eslint. Basically you install the eslint-config-airbnb and add it in the eslintrc like this https://github.com/react-bootstrap/react-bootstrap/blob/master/.eslintrc#L2

**Comment by tnrich** [comment]
Ah, I see. Sounds good.

**Comment by dozoisch** [comment]
Alright! I'm on it
