### ISSUE TITLE
Few Ideas

### ISSUE THREAD

**Issue by dozoisch** [tnrich/react-variable-height-infinite-scroller#9]
I'm thinking about adding an onScroll prop function, that would send the current visible element. This could help triggering something on row visibility change (eg: in my case I want to change the header).

Basically:
- in onEditorScroll     `this.props.onScroll(typeof newRowStart === 'undefined' ? this.rowStart : newRowStart);` 
- and a default onScroll prop that equals a no-op function. 

---

Also, would be nice to be able to customize classNames for different containers

Maybe default props to the current classNames and add
- `containerClassName`
- `rowsContainerClassName`
- `topSpacerClassName`
- `bottomSpaceClassName`

Or maybe it's kind of overkill for all of them. So it could be only for the outmost container

---

I'll put up a PR when I can

**Comment by tnrich** [comment]
Those all sound like totally reasonable ideas. Maybe just the outermost container could get its own classname. I could see it getting a little confusing with everything being passed their own classnames.

**Comment by dozoisch** [comment]
Sure!

Actually, I just tried the onScroll and because of buffering the newRowStart/rowStart might be rows that are offscreen. Is there way to know the first visible row right now?

**Comment by tnrich** [comment]
There isn't a way to tell what the first visible row is currently.

**Comment by dozoisch** [comment]
Alright, I'll add the className on container and the callback first. Then I'll try to see if there is a way to do it, or document a way to implement it from the callback

**Comment by tnrich** [comment]
Sounds good
